name: 'DEV DEPLOY'

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: ${{ vars.AWS_ASSUME_ROLE_ARN }}
      aws-region: us-east-1
      aws-statefile-s3-bucket: ${{ vars.STATEFILE_S3_BUCKET }}
      aws-lock-dynamodb-table: ${{ vars.LOCK_DYNAMODB_TABLE }}
