name: 'PROD DEPLOY'

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: ${{ vars.AWS_ASSUME_ROLE_ARN }}
      aws-region: us-east-1
      aws-statefile-s3-bucket: ${{ vars.STATEFILE_S3_BUCKET }}
      aws-lock-dynamodb-table: ${{ vars.LOCK_DYNAMODB_TABLE }}
